language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean source:jar deploy --settings travis_settings.xml

# travis encrypt -r bootique/bootique-swagger "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-swagger "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "BOTaPOcbmZmiHjHCpYles3zQ2go9KPxearpslGlhrcVf9w2If7og9PFAhKCOgwJKi0l3PCWVHTeON1jcYDGNazuyIa4ghvhfdGoHgg66O+hy7Fx7Zx0VTV4Hu2JqPMkAHizEvP6etxtQbwyFGLnD2jP2EVbwdMbIEo+BmcLTV2sP24MQgifcp1GUz/jW4Qd/6AJAJkBr2T90EUXfAqnWavpWTiL/Rrk4XQgVPydaB/DN2MDmobXichw0vi8Vs8TNcsBqEHnNoYGXaoJsCECX4RF2MUW/J0fnN/zA3LTbUAyDJNNe33ljod811Laf9Y/wEnS9ah31Nki/FOArhzLYhsgGHvA0VzHoojj+azZRL2echbptxKXQLFIv3I5vG4XZFUDdhzzxXyLbDONKaZag0cYrMNNnFkrMzu9BMAv8pM6rViW7mrLaTp0DX0bTeREr1doJcmiBVlHnL16580ASAjQyMGjC85C3Y57XVhZKZCJXX9JNCQTdJyhiWBG+YMUkC5nKlau7W1pQr36ITclZJJLD7fUQBgsx+6p8WN8PWBo+8iPxbLsQtv0Wt1AmxhVOknemA9mhbJj/9Gale5bcgSGIVt35GOaNESa8HWAukEReaqani6m47HjaUXgcYSkeJ6WJAjkgjqxADfZvo6ffLHQM8RQ3qe8kgnwWy0klMQE="
    - secure: "sF2IahGk4SV9sASexD/VA20Enc+Q/K5OM/lf3+IqqAIL43/mByzzZCIhUt1avtvds5teA3oiHBagfBayH4Eiscn5aK+IYnaZEjN9mAYCjHeUFDqyAc98EFnnlmUeIupBwGspgw1iJcSTrp1qoAPp8BiJIUqcKt+/UrqA6MdVCtf1rbREFB6FlXUwXJSuAUOV6UgrkH9N01EbCN4pn6CMgNHy5dRPrilzzgDo4Py5MCV9etXigmNUosLyCAuzdHlB511Kcfput2gnGd6siuql5tdrUTQtLsksWynjR0AbwlB5+mOPIZ/U/LV01KBrUysCa7QIRlLxpnO8eiH0IyKrt2XurrwP9gXm8f46Q4082yblIVIo34CSbdkN+gRpg5igcm6bwRRHsFzjnxYtQMskg5IoA2n+5Q/ii2Rhel0+FcqeXwNiHmAc6z5Rlq+ihm526utbPEp5WKXAK+YPVJf+9qTSqp927gJpAE4F011gN/whsoJfGv91FjKkuv42BbbXPB2UfM3xnIpRh5AiDA2dt99XHXq3EIeesnEaeNKpHElamjIrMQyo+G7kceS+xrPmW717f3ebT880b8thWJWAxU6Wus3VLA9sX9vSqFHyhZUoS+vTaOc0oizNkF3asYbVasQXvnUfENkbUmk3fHlmwj0rgeOpc0AHSp5oPBX1z08="

